# Generated by Django 4.1.4 on 2023-02-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testbot',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_bot', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
